# Amount of slab-items returned when converting a normal block
slabRatio: 1

# Enable owners of slabs (only owners or players with permission "advancedslabs.editall" can edit the slab)
slabOwners: true

items:
  editor:
    wand:
      type: "STICK"
      meta:
        display: "&bEditor Wand"
        lore:
        - "&7Right-Click to edit!"
recipes:
  editor:
    wand:
      shape:
      - "rsr"
      - "rsr"
      - " s "
      ingredients:
        r:
          type: "REDSTONE"
        s:
          type: "STICK"
  placement:
    block:
      shape:
      - "rrr"
      - "rbr" ## b will get replaced with the used slab-material
      - "rrr"
      ingredients:
        r:
          type: "REDSTONE"
messages:
  editor:
    editing: "&aYou are now editing this block."
    finished: "&aYou are no longer editing."
    scrollSteps: "&eSteps: &7%s"
    locationInfo: "&ex: &7%s&e, y: &7%s&e, Z: &7%s"
    error:
      solidBlock: "&eSorry, you cannot place this block above a solid block."
      noPermission: "&cYou cannot edit this block."
  # Prefix for block items (e.g. &bAdvancedSlab: &eSTONE)
  blockPrefix: "&bAdvancedSlab: &e"